<?php
// $Id$

/**
 * @file
 *
 * Allow access control for Drupal book nodes.
 *
 * Based on forum_access.module and tac_lite.module
 *
 */

/**
 * Implementation of hook_help()
 */
function book_access_help($section) {
  switch ($section) {
    case 'admin/content/book/access':
      return t('
        <p>Configure access control per book based on user roles. Settings
        affect all pages within the given book. If a page is moved into a
        different book, it will assume that book\'s access control settings.</p>
        <p>Disabled settings result from conflicts with the book modules access
        settings. See !book_access_help for more information.</p>
        ',  array(
              '!book_access_help' => l(t('Book Access help'), 'admin/help/book_access'),
              '!book_access_settings' => l(t('Book Access settings'), 'admin/content/book/access'),
            )
      );
      break;
    case 'admin/help#book_access':
      return t('
        <p>Allows fine grained access control for Drupal books.</p>
        <p>Certain core access settings provided by book can conflict with access control
        provided by this module. Where a conflict exists, the corresponding settings will be
        disabled on the !book_access_settings page.<p>
        <p>To allow the Book access module to control various settings, you may
        have to disable certain book permissions in the standard
        !access_settings page.<p>
        <p>Requirements are as follows:</p>
        <blockquote>
        <dt>View this book</dt><dd>no conflicts</dd>
        <dt>Create pages in book</dt><dd>Disable: "create book pages"</dd>
        <dt>Edit pages in book</dt><dd>Disable: "edit book pages"</dd>
        <dt>Delete pages in book</dt><dd>Disable: "edit book pages"</dd>
        </blockquote>
        <p>The following book module access settings have no impact on Book
        access settings: "create new books", "edit own pages", "edit own books",
        outline posts in books", "see printer-friendly version".</p>
        <p>Similarly, other access control modules can also impact functionality
        of this module. Broad reaching modules such as "taxonomy access" and
        "content access" can override the values set in the
        !book_access_settings page. You must turn off all enabled access
        controls in such modules.
        ', array(
              '!book_access_help' => l(t('Book Access help'), 'admin/help/book_access'),
              '!book_access_settings' => l(t('Book Access settings'), 'admin/content/book/access'),
              '!access_settings' => l(t('Access settings'), 'admin/user/access'),
            )

      );
      break;
  }
}

/**
 * Implementation of hook_perm().
 *
 */
function book_access_perm() {
  return array('administer book access');
}

/**
 * Implementation of hook_menu().
 *
 */
function book_access_menu($may_cache) {

  if ($may_cache) {
    // we create an additional tab in the book admin page
    $items[] = array(
      'path'               => 'admin/content/book/access',
      'title'              => t('Access control'),
      'callback'           => 'drupal_get_form',
      'callback arguments' => array('book_access_admin_form'),
      'type'               => MENU_LOCAL_TASK,
      'weight'             => 7,
      'access'             => user_access('administer book access'),
    );
  }

  return $items;
}

/**
 * This function supplies the book access grants. book_access simply uses
 * roles as grant IDs.
 */
function book_access_node_grants($user, $op) {
  $grants['book_access'] = array_keys($user->roles);
  return $grants;
}

/**
 * Implementation of hook_node_access_records
 *
 * Returns a list of grant records for the passed in book node object. If we
 * have a book child page, we return the access settings of the top level parent.
 * Checks to see if maybe we're being disabled.
 */
function book_access_node_access_records($node) {
  if (!book_access_enabled()) {
    return;
  }

  if ($node->type == 'book') {
    $parent_nid = _book_access_get_book_nid($node->nid);

    $result = db_query('SELECT * FROM {book_access} WHERE nid = %d', $parent_nid);
    while ($grant = db_fetch_object($result)) {
      $grants[] = array(
        'realm'        => 'book_access',
        'gid'          => $grant->rid,
        'grant_view'   => $grant->grant_view,
        'grant_update' => $grant->grant_update,
        'grant_delete' => $grant->grant_delete
      );
    }

    return $grants;
  }
}

/**
 * Book access configuration page.
 *
 */
function book_access_admin_form() {
  $form = array();
  $rids = array();
  $books = array();

  drupal_add_css(drupal_get_path('module', 'book_access') . '/book_access.css');

  // Get a list of roles (which act as grant IDs)
  $results = db_query("SELECT r.rid, r.name FROM {role} r ORDER BY r.name");
  while ($result = db_fetch_object($results)) {
    $rids[$result->rid] = $result->name;
  }

  // Get listing of books, each of which will have it's own access settings
  $sql = "
    SELECT n.nid, n.title
    FROM {node} n
    LEFT JOIN {book} b ON n.vid = b.vid
    WHERE b.parent = 0
    ORDER BY b.weight ASC
  ";

  $book_results = db_query($sql);

  while ($book = db_fetch_object($book_results)) {
    $books[$book->nid] = $book->title;
  }

  // Each book has its own access control settings
  foreach ($books as $book_nid => $book_name) {

    // used to store existing grants for this book
    $view   = array();
    $update = array();
    $delete = array();
    $create = array();

    $result = db_query("SELECT * FROM {book_access} where nid = %d", $book_nid);

    // if no existing grants, use some safe defaults
    if (db_num_rows($result) == 0) {
      $view   = array(1, 2);
      $update = array();
      $delete = array();
      $create = array();
    }
    else {
      while ($book_access = db_fetch_object($result)) {
        if ($book_access->grant_view) {
          $view[] = $book_access->rid;
        }
        if ($book_access->grant_update) {
          $update[] = $book_access->rid;
        }
        if ($book_access->grant_delete) {
          $delete[] = $book_access->rid;
        }
        if ($book_access->grant_create) {
          $create[] = $book_access->rid;
        }
      }
    }

    // standard access control settings for the book module will conflict with
    // our settings, so we need to know which settings are currently being used
    // and notify the admin and disable our control of those settings until
    // conflicts have been resolved
    $enabled_perms = _book_access_get_enabled_permissions();

    $form['#tree'] = TRUE;

    $form['access'][$book_nid] = array(
      '#type'        => 'fieldset',
      '#title'       => $book_name,
      '#collapsible' => TRUE,
    );

    $form['access'][$book_nid]['view'] = array(
      '#type'          => 'checkboxes',
      '#prefix'        => '<div class="book-access-div">',
      '#suffix'        => '</div>',
      '#options'       => $rids,
      '#title'         => t('View this book'),
      '#default_value' => $view
    );

    if ($enabled_perms['create book pages'] == TRUE) {
      $form['access'][$book_nid]['create'] = array(
        '#type'          => 'markup',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#title'         => t('View this book'),
        '#value'         => '<p>' . t('Edit pages in this book: Disabled') . '</p>',
      );
    }
    else {
      $form['access'][$book_nid]['create'] = array(
        '#type'          => 'checkboxes',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#options'       => $rids,
        '#title'         => t('Create pages in this book'),
        '#default_value' => $create
      );
    }

    if ($enabled_perms['edit book pages'] == TRUE) {
      $form['access'][$book_nid]['update'] = array(
        '#type'          => 'markup',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#value'         => '<p>' . t('Edit pages in this book: Disabled') . '</p>',
      );
    }
    else {
      $form['access'][$book_nid]['update'] = array('#type' => 'checkboxes',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#options'       => $rids,
        '#title'         => t('Edit pages in this book'),
        '#default_value' => $update
      );
    }

    if ($enabled_perms['edit book pages'] == TRUE) {
      $form['access'][$book_nid]['update'] = array(
        '#type'          => 'markup',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#value'         => '<p>' . t('Delete pages in this book: Disabled') . '</p>',
      );
    }
    else {
      $form['access'][$book_nid]['delete'] = array('#type' => 'checkboxes',
        '#prefix'        => '<div class="book-access-div">',
        '#suffix'        => '</div>',
        '#options'       => $rids,
        '#title'         => t('Delete pages in this book'),
        '#default_value' => $delete
      );
    }
  }

  $form['clearer'] = array(
    '#value' => '<div class="book-access-clearer"></div>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function book_access_admin_form_submit($form_id, $form_values) {

  foreach($form_values['access'] as $book_nid => $form) {
    db_query("DELETE FROM {book_access} WHERE nid = %d", $book_nid);

    foreach ($form['view'] as $rid => $checked) {
      $gid = $rid;
      $grant_view = (bool) $checked;
      $grant_create = $form['create'][$rid] > 0 ? TRUE : FALSE;
      $grant_update = $form['update'][$rid] > 0 ? TRUE : FALSE;
      $grant_delete = $form['delete'][$rid] > 0 ? TRUE : FALSE;

      $sql = "
        INSERT INTO {book_access} (nid, rid, grant_view, grant_update, grant_delete, grant_create)
        VALUES (%d, %d, %d, %d, %d, %d)
      ";

      db_query($sql, $book_nid, $rid, $grant_view, $grant_update, $grant_delete, $grant_create);
    }
  }
  node_access_rebuild();
}

/**
 * This is also required by ACL module.
 */
function book_access_enabled($set = NULL) {
  static $enabled = true;
  if ($set !== NULL) {
    $enabled = $set;
  }
  return $enabled;
}

/**
 * Implementation of hook_enable
 */
function book_access_enable() {
  node_access_rebuild();
}

/**
 * Implementation of hook_disable
 */
function book_access_disable() {
  book_access_enabled(FALSE);
  node_access_rebuild();
}

/**
 * use hook init to deny access to books if the user does not have access
 * to it.
 */
function book_access_init() {
  if (!function_exists('user_access')) {
    // page is cached; bail.
    return;
  }

  if (!user_access('administer books') && arg(0) == 'book' && is_numeric(arg(1))) {
    global $user;
    if (!book_access_access(arg(1), 'view')) {
      drupal_access_denied();
      module_invoke_all('exit');
      exit;
    }
  }
}

/**
 * Return array of book nodes and their parents.
 */
function _book_access_get_parents() {
  static $parents;

  if (!is_array($parents)) {
    $sql = "
      SELECT n.nid, b.parent
      FROM {node} n
      LEFT JOIN {book} b ON n.vid = b.vid
      WHERE n.type = 'book'
    ";

    $results = db_query($sql);
    while ($result = db_fetch_object($results)) {
      $parents[$result->nid] = $result->parent;
    }
  }

  return $parents;
}

/**
 * Return the very top level (book) nid for a given book page.
 */
function _book_access_get_book_nid($nid) {
  $parents = _book_access_get_parents();

  if ($parents[$nid] == 0) {
    return $nid;
  }
  else {
    return _book_access_get_book_nid($parents[$nid]);
  }
}

/**
 * Returns an array of permissions that are enabled for one or more roles
 */
function _book_access_get_enabled_permissions() {
  $enabled_perms = array();

  $sql = "
    SELECT perm
    FROM {permission}
  ";
  $results = db_query($sql);
  while ($result = db_fetch_array($results)) {
    $perms = split(', ', $result['perm']);
    foreach ($perms as $perm) {
      $enabled_perms[$perm] = TRUE;
    }
  }

  return $enabled_perms;
}
